# Generated by Django 2.2.3 on 2021-04-01 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0003_favouriteregion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='post',
        ),
        migrations.AddField(
            model_name='favourite',
            name='favouriteregion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='favourite.FavouriteRegion'),
        ),
    ]
