# Generated by Django 2.2.3 on 2021-04-01 14:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_remove_post_modified'),
        ('favourite', '0004_auto_20210401_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='favouriteregion',
        ),
        migrations.AddField(
            model_name='favourite',
            name='post',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FavouriteRegion',
        ),
    ]
