# Generated by Django 2.2.3 on 2021-03-24 16:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210324_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='modifield',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 16, 56, 45, 189282, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(editable=False, max_length=150, unique=True),
        ),
    ]
