# Generated by Django 2.2.3 on 2021-03-25 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20210325_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='modified',
        ),
    ]
